name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    env:
      CPATH: C:\Program Files (x86)\WinFsp\inc\fuse
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.0"

      - name: Install winfsp (Windows) # https://github.com/winfsp/cgofuse/blob/master/.github/workflows/test.yml
        run: |
          $releases = Invoke-WebRequest https://api.github.com/repos/winfsp/winfsp/releases | `
              ConvertFrom-Json

          $asseturi = $releases[0].assets.browser_download_url | `
              Where-Object { $_ -match "winfsp-.*\.msi" }
          Invoke-WebRequest -Uri $asseturi -Out winfsp.msi
          Start-Process -NoNewWindow -Wait msiexec "/i winfsp.msi /qn INSTALLLEVEL=1000"

      - name: Build
        run: go build -v -o build/storage-x86_64-pc-windows-msvc.exe

      - name: Test
        run: go test -v ./...

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/storage-x86_64-pc-windows-msvc.exe

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/storage-x86_64-pc-windows-msvc.exe
          asset_name: storage-x86_64-pc-windows-msvc.exe
          asset_content_type: application/octet-stream
