name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    env:
      CPATH: C:\Program Files (x86)\WinFsp\inc\fuse
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.0"

      - name: Install winfsp (Windows) # https://github.com/winfsp/cgofuse/blob/master/.github/workflows/test.yml
        run: |
          $releases = Invoke-WebRequest https://api.github.com/repos/winfsp/winfsp/releases | `
              ConvertFrom-Json

          $asseturi = $releases[0].assets.browser_download_url | `
              Where-Object { $_ -match "winfsp-.*\.msi" }
          Invoke-WebRequest -Uri $asseturi -Out winfsp.msi
          Start-Process -NoNewWindow -Wait msiexec "/i winfsp.msi /qn INSTALLLEVEL=1000"

      - name: Build
        run: go build -v -o build/storage-x86_64-pc-windows-msvc.exe

      - name: Test
        run: go test -v ./...

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/storage-x86_64-pc-windows-msvc.exe

      - name: Create and Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/storage-x86_64-pc-windows-msvc.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
